"""provider status

Revision ID: ce30f05b47c7
Revises: ee9106c1a8bd
Create Date: 2026-09-28 14:44:39.632827
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'ce30f05b47c7'
down_revision = 'ee9106c1a8bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_status',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_status')
    # ### end Alembic commands ###
