"""item article text

Revision ID: 5a9a93bc0185
Revises: ce30f05b47c7
Create Date: 2026-09-28 20:01:07.471979
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '5a9a93bc0185'
down_revision = 'ce30f05b47c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('article_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'article_text')
    # ### end Alembic commands ###
